### PR TITLE
Fix the call to `@trace` in tilde desugaring

### LINKED ISSUE #222: Tilde syntax `x ~ foo` looks for `@trace` in the caller's namespace
Example:
```julia
Gen.@gen function f()
  x ~ Gen.normal(0, 1)
end
# ERROR: LoadError: UndefVarError: @trace not defined
```
I think this is a bug in the macro escaping.

### PR DESCRIPTION
**Pull request by bzinberg**
Fixes https://github.com/probcomp/Gen/issues/222.

Quoting https://github.com/probcomp/Gen/issues/222#issuecomment-606780545:

> I think what should be happening is that `trace` (as a function on ASTs) should be called at macro expansion time, from within Gen's internals. Instead, the desugarer was punting the `@trace`ing to the caller, which actually worked if the caller happened to have `@trace` in their namespace, but was not the intended logic.

## Tested

The minimal example in https://github.com/probcomp/Gen/issues/222#issue-591297488 now works.

### CODE REVIEW

**Comment by ztangent** [comment]
@bzinberg did you test if this works in the SML? I suspect it won't because the static parser explicitly tries to match `@trace` expressions. (The `@trace` macro is only defined [for the DML](https://github.com/probcomp/Gen/blob/964d8a96205de6bb13e69f13eec7eaff7906c952/src/dynamic/dynamic.jl#L63), not the SML.)

(Note that my suggested fix in #222 might not work for the SML either..., because it probably won't parse `Gen.@trace` as `@trace`.)

Separately, is `trace` a function? Can you call something defined as a macro as a function instead...?

**Comment by bzinberg** [comment]
> Separately, is `trace` a function? Can you call something defined as a macro as a function instead...?

Aha!  My understanding was that every Julia macro `@foo` also comes with a function `foo` which operates on ASTs.  Looks like I was wrong (and Gen also has a function called `trace`, which hid this fact from me)!

**Comment by ztangent** [comment]
Finally got around to fixing this (#222) and fixed #235 along the way!

The strategy I ended up using, which works across the DML and SML, was to desugar the tilde syntax to `GlobalRef` versions of the `@trace` macrocall, ensuring that macro-expansion for the DML always accurately looks up the definition of `@trace` in the `Gen` module. 

In addition, the `@gen` macro now pre-resolves all properly-scoped references to `@trace` and `@param` to `GlobalRef` versions. The SML parser then pattern matches against these globally referenced `@trace` and `@param` expressions (whether pre-resolved or desugared from tilde expressions), instead of the unqualified references to `@trace` and `@param`. This means that the SML parser now obeys proper scoping rules for uses of `@trace` and `@param`, which it previously did not. As such, the following examples now compile as expected:
```julia
import Gen
Gen.@gen (static) function f1()
  x = Gen.@trace(Gen.normal(0, 1), :x)
  return x
end

Gen.@gen function f2()
  x  ~ Gen.normal(0, 1)
  return x
end
```
while the following example, which previously would have compiled, now (correctly) throws an UndefVar error for its unqualified use of `@trace`: 
```julia
import Gen
Gen.@gen function f()
  x = @trace(Gen.normal(0, 1), :x)
  return x
end
```

Finally, I added some code that uses `MacroTools.prewalk` to extract and protect any quoted expressions before pre-resolving macros and tilde desugaring, and then re-inserting those quoted expressions after those pre-processing steps. This fixes the issue in #235 where tilde expressions nested within quotes were desugared.

**Comment by ztangent** [comment]
I wanted to add that these changes should also pave the way for supporting macro calls in the SML (as suggested in #185, #184), while still maintaining the correct scoping rules for the surface syntax! 

In particular, now that the SML parser now only sees globally referenced versions of `@trace` and `@param`, we can use MacroTools to match against them, remap them to some other specialized expression (to protect them from macro-expansion), and then perform macro-expansion of all the other code before mapping them back. I was almost going to implement this, but figured I should hold off for a future PR.

File: src/dsl/dsl.jl [hunk 1]
```diff
@@ -71,21 +72,77 @@ function address_from_expression(lhs)
...
+            idx = p.args[1]
+            quoted_exprs[idx]
+        else
+            e
+        end
+    end
+    return expr
+end
+
+function preprocess_body(expr, __module__)
```
Comment (bzinberg) [inline src/dsl/dsl.jl:137]: Could you add your explanation in https://github.com/probcomp/Gen.jl/pull/223#issuecomment-646420005 as a docstring here, or wherever you think it best fits?

**Review by bzinberg — COMMENTED** [review]
Awesome!!

**Comment by alex-lew** [comment]
This is awesome! Today I learned about `GlobalRef` :-) Thanks so much for taking this on, Xuan!

File: src/dsl/dsl.jl [hunk 2]
```diff
@@ -71,21 +72,77 @@ function address_from_expression(lhs)
 end
 
 function desugar_tildes(expr)
+    trace_ref = GlobalRef(@__MODULE__, Symbol("@trace"))
+    line_num = LineNumberNode(1, :none)
```
Comment (alex-lew) [inline src/dsl/dsl.jl:76]: @ztangent Any idea if this changes anything re: error messages? i.e., do crashes still report the right line number for `@trace` calls?

Comment (ztangent) [reply src/dsl/dsl.jl:76]: Pretty sure the previous thing that was being done (where we were constructing `@trace(addr)` expressions as a quoted expression) also wasn't including line numbers!

Comment (ztangent) [reply src/dsl/dsl.jl:76]: Yup, confirmed:
```julia
julia> dump(:(@trace(call, addr)))
Expr
  head: Symbol macrocall
  args: Array{Any}((4,))
    1: Symbol @trace
    2: LineNumberNode
      line: Int64 1
      file: Symbol none
    3: Symbol call
    4: Symbol addr
```

So at the very least it's not a regression.

File: src/dsl/dsl.jl (hunk 1 above)
Comment (ztangent) [reply src/dsl/dsl.jl:137]: Just added explanatory comments to each line. Decided against docstrings for now -- we probably want to add docstrings consistently to all the parsing code at some later point.

**Comment by ztangent** [comment]
@bzinberg @marcoct okay if I go ahead and merge?

**Comment by marcoct** [comment]
Sounds good to me!
